### ISSUE TITLE
Meios de Transmissões do Hardware

### ISSUE THREAD

**Issue by MatheusPiresSalazar** [pji20242/hardware#1]
Verificar os meios de transmissão de dados.

**Comment by MatheusPiresSalazar** [comment]
O processo de pesquisa para transmissão dos dados do Hardware está sendo preenchido no [Organização Hardware](https://docs.google.com/presentation/d/1vVK3PuomsDgRL6gFl0Q_JZFURVGV5Gye9r36CYJlH_Y/edit?usp=sharing).

**Comment by deividffrederico** [comment]
Dados sobre meios [LPWA](https://github.com/pji20242/hardware/blob/main/estudo/meios_lpwa.MD);

**Comment by MatheusPiresSalazar** [comment]
Finalização da pesquisa sobre os possíveis meios de transmissão. [Levantamento das pesquisas](https://github.com/pji20242/hardware/blob/main/estudo/transmiss%C3%A3o.md)
