### ISSUE TITLE
Reconhecimento da quantia de sensores ligadas a ESP32

### ISSUE THREAD

**Issue by RhenzoHideki** [pji20242/hardware#25]

**Comment by deividffrederico** [comment]
Foram realizadas várias buscas por soluções unificadas para a detecção dos sensores conectados as portas do ESP32. Entre elas a busca por bibliotecas para a solução, e em nenhum caso foi possível contemplar todos os pinos da ESP. Uma vez que seus pinos trabalham com diferentes protocolos de comunicação como SPI, I2C e I2S.
Outra possível solução seria via hardware conectando mecanismos de pull up e pull down para cada pino.

Acredito que a melhor solução será implementar caso a caso. Boa parte dos sensores podem realizar a verificação via biblioteca propria. Os que não incluem possibilidade via  software serão resolvidos com o uso do pull-up ou pull-down.

Segue link com detalhes interessantes sobre os pinos e especifidades que devemos observar:
https://lastminuteengineers.com/esp32-pinout-reference/
